# Generated by Django 2.0.6 on 2018-07-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_auto_20180703_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recoursename', models.CharField(max_length=50)),
                ('recoursetime', models.CharField(max_length=8)),
                ('recourseprice', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
